name: SimpleTPA
version: '1.0-SNAPSHOT'
main: com.jellypudding.simpleTPA.SimpleTPA
api-version: '1.21'
description: "Implements simple TPA commands with 2-minute request timeouts"
author: AlphaAlex115

commands:
  tpa:
    description: Request to teleport to another player
    usage: /tpa <player>
    permission: simpletpa.tpa
  tpaccept:
    description: Accept a pending teleport request
    usage: /tpaccept <player>
    permission: simpletpa.tpaccept

permissions:
  simpletpa.tpa:
    description: Allows players to request teleportation to other players
    default: op
  simpletpa.tpaccept:
    description: Allows players to accept teleport requests
    default: op