name: SimpleTPA
version: '1.3'
main: com.jellypudding.simpleTPA.SimpleTPA
api-version: '1.21'
description: "Implements simple TPA commands with 2-minute request timeouts"
author: AlphaAlex115
website: www.minecraftoffline.net

commands:
  tpa:
    description: Request to teleport to another player
    usage: /tpa <player>
    permission: simpletpa.tpa
  tpaccept:
    description: Accept a pending teleport request
    usage: /tpaccept <player>
    permission: simpletpa.tpaccept
  tpdeny:
    description: Deny a pending teleport request
    usage: /tpdeny <player>
    permission: simpletpa.tpdeny
  tpacancel:
    description: Cancel your own teleport request
    usage: /tpacancel [player|all]
    permission: simpletpa.tpacancel

permissions:
  simpletpa.tpa:
    description: Allows players to request teleportation to other players
    default: true
  simpletpa.tpaccept:
    description: Allows players to accept teleport requests
    default: true
  simpletpa.tpdeny:
    description: Allows players to deny teleport requests
    default: true
  simpletpa.tpacancel:
    description: Allows players to cancel their own teleport requests
    default: true